#!/usr/bin/env python3

from argparse import ArgumentParser
from importer import Importer, TransactionMatcher
from pathlib import Path
import importlib.util
import os
import sys
import workbook

def main():

    actions = [
        'import',
        'reimport',
        'post',
        'gen-mergefiles',
        'merge-edits',
        'workbook',
    ]

    parser = ArgumentParser()
    parser.add_argument('action', choices=actions)
    parser.add_argument('files', nargs='*')
    parser.add_argument('--data-dir', default=os.environ.get('SLOWBOOKS_DATA', None))
    args = parser.parse_args()

    data_dir = Path(args.data_dir)
    if not data_dir.is_dir():
        print(f'Data dir {data_dir} not found. Exiting')
        sys.exit(1)

    if args.action == 'import':
        _get_importer(data_dir).import_transactions()
    elif args.action == 'reimport':
        _get_importer(data_dir).reimport_transactions(args.files)
    elif args.action == 'post':
        _get_importer(data_dir).post_to_journal()
    elif args.action == 'merge-edits':
        _get_importer(data_dir).merge_edits()
    elif args.action == 'gen-mergefiles':
        _get_importer(data_dir).generate_mergefiles(args.files)
    elif args.action == 'workbook':
        workbook.run_workbook(data_dir)
    else:
        raise RuntimeError('Bad command')

def _get_importer(data_dir):
    matcher_plugin_file = data_dir / 'user_code/matcher_plugin.py'
    matcher_plugin = None
    try:
        spec = importlib.util.spec_from_file_location('matcher_plugin', matcher_plugin_file)
        module = importlib.util.module_from_spec(spec)
        spec.loader.exec_module(module)
        matcher_plugin = module.MatcherPlugin()
    except Exception as e:
        print(f'Failed to load plugin from {matcher_plugin_file}, using defaults.\n{str(e)}')

    return Importer(data_dir=data_dir,
                    transaction_matcher=TransactionMatcher(matcher_plugin))

if __name__ == '__main__':
    main()
